### ISSUE TITLE
Version not compatible with the latest firebase dependencies

### ISSUE THREAD

**Issue by NabinStha2** [khalti/checkout-sdk-flutter#5]
Because firebase_crashlytics >=3.5.3 depends on firebase_core ^2.30.1 which depends on firebase_core_web ^2.16.0, firebase_crashlytics >=3.5.3 requires firebase_core_web ^2.16.0.
And because firebase_core_web >=2.12.0 depends on web ^0.5.1, firebase_crashlytics >=3.5.3 requires web ^0.5.1.
Because package_info_plus 5.0.1 depends on web >=0.3.0 <0.5.0 and no versions of package_info_plus match >5.0.1 <6.0.0, package_info_plus ^5.0.1 requires web >=0.3.0 <0.5.0.
Thus, firebase_crashlytics >=3.5.3 is incompatible with package_info_plus ^5.0.1.
And because khalti_checkout_core 1.0.0-dev.3 depends on package_info_plus ^5.0.1 and no versions of khalti_checkout_core match >1.0.0-dev.3 <2.0.0, firebase_crashlytics >=3.5.3 is incompatible with khalti_checkout_core ^1.0.0-dev.3.
And because khalti_checkout_flutter 1.0.0-dev.4 depends on khalti_checkout_core ^1.0.0-dev.3 and no versions of khalti_checkout_flutter match >1.0.0-dev.4 <2.0.0, firebase_crashlytics >=3.5.3 is incompatible with khalti_checkout_flutter ^1.0.0-dev.4.
So, because bhumi_earth_app depends on both khalti_checkout_flutter ^1.0.0-dev.4 and firebase_crashlytics ^3.5.4, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on firebase_crashlytics: flutter pub add firebase_crashlytics:^3.4.18

**Comment by Biplab-Dutta** [comment]
It seems you can solve the issue by [overriding the dependency constraint](https://dart.dev/tools/pub/dependencies#dependency-overrides). Please provide us a minimum reproducible sample. We can then further investigate. Thanks.
