### ISSUE TITLE
SDK Version Dependency problem

### ISSUE THREAD

**Issue by prabesh605** [khalti/checkout-sdk-flutter#6]
![image](https://github.com/khalti/checkout-sdk-flutter/assets/47147134/e53e1980-39c5-4de2-8b75-c48ea6ae662b)

our application is in older version of flutter. Its hard for us to upgrade instantly as there are lots of dependency in the project. So what could we do please help.
Thank you!

**Comment by pandeykushal** [comment]
have you make the khalti v2 worke ??

**Comment by prabesh605** [comment]
I upgrade my flutter version and solve some dependency confict manually and I was able to use this package.

**Comment by Biplab-Dutta** [comment]
Please upgrade your flutter to get rid of the issue. Thank you
