### ISSUE TITLE
Cannot Get Login interface in khalti_checkout_flutter 

### ISSUE THREAD

**Issue by Nikhil369369** [khalti/checkout-sdk-flutter#7]
**Describe the bug**

**To Reproduce**
1. Go to 'using example code cannot login '

**Comment by Biplab-Dutta** [comment]
Hi  @Nikhil369369 Can you elaborate the issue. It's unclear.

**Comment by Biplab-Dutta** [comment]
Closing the issue as the developer didn't respond. If there's any issue you encountered in the future again, please file a new issue.

**Comment by iamsagar14** [comment]
i am facing same issue 
there is o interface for login and all 
directly payment succussfully appears

**Comment by Biplab-Dutta** [comment]
Yes. There is no UI for login because when a pidx is generated via a server side POST request, you pass everything necessary to be able to make a transaction.
